[workspace]
resolver = "2"

members = ["arceos-vmm"]

[profile.release]
lto = true

[workspace.dependencies]
axalloc = { git = "https://github.com/arceos-hypervisor/arceos.git", rev = "8f55599a" }
axhal = { git = "https://github.com/arceos-hypervisor/arceos.git", rev = "8f55599a" }
axstd = { git = "https://github.com/arceos-hypervisor/arceos.git", rev = "8f55599a" }
axtask = { git = "https://github.com/arceos-hypervisor/arceos.git", rev = "8f55599a" }

axvm = { git = "https://github.com/arceos-hypervisor/axvm.git", rev = "47fb6e3" }
axvcpu = { git = "https://github.com/arceos-hypervisor/axvcpu.git", rev = "f7e5615" }
axaddrspace = { git = "https://github.com/arceos-hypervisor/axaddrspace.git" }

arm_vcpu = { git = "https://github.com/arceos-hypervisor/arm_vcpu.git" }
x86_vcpu = { git = "https://github.com/arceos-hypervisor/x86_vcpu.git", rev = "b962aea" }
riscv_vcpu = { git = "https://github.com/arceos-hypervisor/riscv_vcpu.git" }

# [patch."https://github.com/arceos-hypervisor/arceos.git"]
# axtask = { path = "../arceos/modules/axtask" }
# axalloc = { path = "../arceos/modules/axalloc" }
# axhal = { path = "../arceos/modules/axhal" }
# axstd = { path = "../arceos/ulib/axstd" }

# [patch."https://github.com/arceos-hypervisor/axvm.git"]
# axvm = { path = "../arceos-crates/axvm" }

# [patch."https://github.com/arceos-hypervisor/axvcpu.git"]
# axvcpu = { path = "../arceos-crates/axvcpu" }

# [patch."https://github.com/arceos-hypervisor/x86_vcpu.git"]
# x86_vcpu = { path = "../arceos-crates/x86_vcpu" }
